version: 3

interval: 100ms

vars:
    CU: '{{if eq OS "windows"}}coreutils {{end}}'
    EXE: '{{if eq OS "windows"}}.exe{{end}}'

tasks:
    default:
        watch: true
        sources:
            - "**/*.odin"
        cmds:
            - cmd: clear
            - cmd: "{{.CU}}cp ./tests/*.odin ."
              silent: true
            - cmd: odin test . -vet -strict-style

    test:
        cmds:
            - cmd: "{{.CU}}cp ./tests/*.odin ."
              silent: true
            - defer: { task: clean }
            - cmd: odin test . -vet -strict-style

    bench:
        cmds:
            - odin build . -o:speed
            - ./2024{{.EXE}} -benchmark
            - defer: { task: clean }

    bench-*:
        vars:
            SOLUTION: "{{index .MATCH 0 | upper}}"
        cmds:
            - odin run . -- -solution={{.SOLUTION}} -benchmark
            - defer: { task: clean }

    clean:
        cmds:
            - cmd: "{{.CU}}rm -f *_test.odin"
              silent: true
            - cmd: "{{.CU}}rm -f 2024{{.EXE}} || true"
              silent: true
