version: 3

interval: 100ms

vars:
    CU: '{{if eq OS "windows"}}coreutils {{end}}'
    EXE: '{{if eq OS "windows"}}.exe{{end}}'

tasks:
    default:
        watch: true
        sources:
            - "**/*.odin"
        cmds:
            - cmd: clear
            - cmd: "{{.CU}}cp ./tests/*.odin ."
              silent: true
            - defer: { task: clean }
            - cmd: odin test . -vet -strict-style -define:ODIN_TEST_FANCY=false

    test:
        cmds:
            - cmd: "{{.CU}}cp ./tests/*.odin ."
              silent: true
            - defer: { task: clean }
            - cmd: odin test . -vet -strict-style -define:ODIN_TEST_FANCY=false

    bench:
        cmds:
            - odin build . -o:speed
            - ./2024{{.EXE}} -benchmark
            - defer: { task: clean }

    bench-*:
        vars:
            SOLUTION: "{{index .MATCH 0 | upper}}"
        cmds:
            - odin run . -- -solution={{.SOLUTION}} -benchmark
            - defer: { task: clean }

    profile-*:
        vars:
            SOLUTION: "{{index .MATCH 0 | upper}}"
        cmds:
            - cmd: |
                  sed -i '/\/\/ <PROFILE IMPORTS>/a\
                  import "base:runtime"\
                  import "core:prof/spall"\
                  import "core:sync"' main.odin
              silent: true
            - odin build . -o:speed -define:PROFILE=true
            - ./2024{{.EXE}} -benchmark -solution={{.SOLUTION}}
            - defer: { task: clean-profile }

    clean-profile:
        cmds:
            - cmd: |
                  sed -i '/import.*runtime/d' main.odin
                  sed -i '/import.*spall/d' main.odin
                  sed -i '/import.*sync/d' main.odin
              silent: true
            - task: clean

    clean:
        cmds:
            - cmd: "{{.CU}}rm -f *_test.odin"
              silent: true
            - cmd: "{{.CU}}rm -f 2024{{.EXE}} || true"
              silent: true
