name: CI
on: push

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: arduino/setup-task@v2
            - uses: laytan/setup-odin@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Report
              run: |
                  odin report ./2021
                  odin report ./2024
            - name: Test
              run: |
                  cd 2021 && task
                  cd ../2024 && task

    statistics:
        needs: test
        name: Benchmark and Update Readme
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: arduino/setup-task@v2
            - uses: laytan/setup-odin@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - run: cd 2021 && task bench
            - run: cd 2022 && go build .
            - run: cd 2022 && ./aoc2022 -benchmark
            - run: cd 2023 && go build .
            - run: cd 2023 && ./aoc2023 -benchmark
            - run: cd 2024 && task bench
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Update readme statistics
