name: Generate Statistics Tables for Readme
on: push

jobs:
  statistics:
    name: Benchmark and Update Readme
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: cd 2022 && go build .
      - run: cd 2022 && aoc2022
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update readme statistics
